### ISSUE TITLE
Refresh recyclerview - Swipe/Drag problems 

### ISSUE THREAD

**Issue by strangerweather** [Rishabhk07/Recycler-swipe-drag#2]
First of all, many thanks for this very easy swipe-drag library!

What's the best way of refreshing the recyclerview? When I reload my data, the swipe/drag functionality malfunctions. For instance, swipe works but items do not move back into position and I am left with a gap where the swiped card was. And dragging is sluggish and does not work well.

To reload the recyclerview, I use the exact same method as to load it. Any tips? Thanks!

**Comment by ParryPatel021** [comment]
@strangerweather have you got some workaround?
I am also facing the same problem as you are saying.
can't have an idea about how to resolve it.

**Comment by strangerweather** [comment]
@ParryPatel021 Sorry, I can't remember, that was 2 years ago. I think I just used a different library. I don't have that project anymore so I can't check.

**Comment by ParryPatel021** [comment]
@strangerweather Thanks for the reply. I have solved my problem to prevent the attachment of  ItemTouchHelper to RecyclerView multiple times. 
In short, I have attached ItemTouchHelper to RecyclerView by putting it in onCreate() method of an Activity.
